// Generated by scripts/generate-loader-map.mjs from the Thunderstore ecosystem schema.
// Do not edit by hand: it states which packages ship each mod loader.
export const LOADER_PACKAGES: Record<string, string[]> = {
  "bepinex": [
    "1F31A-BepInEx_Valheim_Full",
    "bbepis-BepInEx_Rogue_Tower",
    "bbepis-BepInExPack",
    "bbepisTaleSpire-BepInExPack",
    "BepInEx_Wormtown-BepInExPack",
    "BepInEx-BepInExPack",
    "BepInEx-BepInExPack_AcrossTheObelisk",
    "BepInEx-BepInExPack_Aeruta",
    "BepInEx-BepInExPack_AGAINST",
    "BepInEx-BepInExPack_Aloft",
    "BepInEx-BepInExPack_AmongUs",
    "BepInEx-BepInExPack_BadNorth",
    "BepInEx-BepInExPack_CaLABP",
    "BepInEx-BepInExPack_Chrono_Ark",
    "BepInEx-BepInExPack_Core_Keeper",
    "BepInEx-BepInExPack_CrabGame",
    "BepInEx-BepInExPack_CultOfTheLamb",
    "BepInEx-BepInExPack_EtG",
    "BepInEx-BepInExPack_FootballManager26",
    "BepInEx-BepInExPack_ForTheKing",
    "BepInEx-BepInExPack_GTFO",
    "BepInEx-BepInExPack_H3VR",
    "BepInEx-BepInExPack_HOTDS",
    "BepInEx-BepInExPack_HumanFallFlat",
    "BepInEx-BepInExPack_IL2CPP",
    "BepInEx-BepInExPack_Inscryption",
    "BepInEx-BepInExPack_InSilence",
    "BepInEx-BepInExPack_LensIsland",
    "BepInEx-BepInExPack_LLBlaze",
    "BepInEx-BepInExPack_LostSkies",
    "BepInEx-BepInExPack_Magicite",
    "BepInEx-BepInExPack_Muck",
    "BepInEx-BepInExPack_Mycopunk",
    "BepInEx-BepInExPack_NASB",
    "BepInEx-BepInExPack_NearlyDead",
    "BepInEx-BepInExPack_Necropolis",
    "BepInEx-BepInExPack_Ostranauts",
    "BepInEx-BepInExPack_Outward",
    "BepInEx-BepInExPack_Patapon",
    "BepInEx-BepInExPack_PEAK",
    "BepInEx-BepInExPack_Peglin",
    "BepInEx-BepInExPack_PotionCraft",
    "BepInEx-BepInExPack_Ravenfield",
    "BepInEx-BepInExPack_RogueGenesia",
    "BepInEx-BepInExPack_ROUNDS",
    "BepInEx-BepInExPack_Silksong",
    "BepInEx-BepInExPack_Skul",
    "BepInEx-BepInExPack_SlashersKeep",
    "BepInEx-BepInExPack_Stacklands",
    "BepInEx-BepInExPack_Starsand",
    "BepInEx-BepInExPack_TABS",
    "BepInEx-BepInExPack_Thronefall",
    "BepInEx-BepInExPack_Timberborn",
    "BepInEx-BepInExPack_TromboneChamp",
    "BepInEx-BepInExPack_V_Rising",
    "BepInEx-BepInExPack_VTOL_VR",
    "BepInEx-BepInExPack_WizardWithAGun",
    "BepInEx-BepInExPack_x86",
    "BepInExPackMTD-BepInExPack_20MTD",
    "denikson-BepInExPack_Valheim",
    "GoblinCleanupModding-BepInExPack_GoblinCleanup",
    "grime_modding-BepInExPack_Grime",
    "Modding_Council-BepInExPack_of_Legend",
    "PCVR_Modders-BepInExPack_GHVR",
    "Romestead_Modding-BepInExPack_Romestead",
    "SFTG_Modding-BepInExPack_SFTG",
    "silksong_modding-BepInExPack_Silksong",
    "SlipSkid_Modding-BepInExPack_SlipSkid",
    "Subnautica_Modding-BepInExPack",
    "Subnautica_Modding-BepInExPack_BelowZero",
    "Subnautica_Modding-BepInExPack_Subnautica",
    "Subnautica_Modding-BepInExPack_Subnautica_Experimental",
    "SunkenlandModding-BepInExPack_Sunkenland",
    "xiaoxiao921-BepInExPack",
    "xiaoye97-BepInEx",
    "Zinal001-BepInExPack_MECHANICA"
  ],
  "bepisloader": [
    "ResoniteModding-BepInExRenderer",
    "ResoniteModding-BepisLoader"
  ],
  "gdweave": [
    "NotNet-GDWeave"
  ],
  "godotml": [
    "GodotModding-GodotModLoader"
  ],
  "lovely": [
    "Thunderstore-lovely"
  ],
  "melonloader": [
    "LavaGang-MelonLoader"
  ],
  "northstar": [
    "northstar-Northstar"
  ],
  "recursive-melonloader": [
    "HomeSafetyHotline_Modding-MelonLoader_HomeSafetyHotline",
    "LavaGang-MelonLoader",
    "SHMCD_Modding-MelonLoader_SHMCD"
  ],
  "return-of-modding": [
    "Hell2Modding-Hell2Modding",
    "ReturnOfModding-ReturnOfModding"
  ],
  "rivet": [
    "ReDoIngMods-Rivet"
  ],
  "shimloader": [
    "0xFFF7-votv_shimloader",
    "Thunderstore-unreal_shimloader"
  ],
  "umm": [
    "ADOFAI_Modding-UMM_ADOFAI",
    "UMM-UMM"
  ]
};
